#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("P2_TMurphy_Cam.Resource", IsApplication=true)]

namespace P2_TMurphy_Cam
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_add_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_add_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_add_red = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_add_rnd_noise = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_blur = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_flip_horiz = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_flip_vert = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_grayscale = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_high_contrast = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_negate_blue = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_negate_green = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_negate_red = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_pixelate = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_pointillism = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_remove_blue = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_remove_green = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_remove_red = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_rotate_90 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_tint = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn_woodgrain = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int gridView = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int launchCameraButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int takenPictureImageView = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
