#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("P1_TMurphy_Calc.Resource", IsApplication=true)]

namespace P1_TMurphy_Calc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_bttm_dcpnt = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_bttm_plsmns = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_num_0 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_num_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_num_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_num_3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_num_4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_num_5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_num_6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_num_7 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_num_8 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_num_9 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_rght_optr_add = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_rght_optr_div = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_rght_optr_eql = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_rght_optr_mltp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_rght_optr_sub = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_top_ac = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_top_c = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn_top_prc = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int calcDisplay = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int gridView = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
